# Generated by Django 4.1.10 on 2023-09-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_followrelation_user_follow"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="followrelation",
            constraint=models.UniqueConstraint(fields=("following_user", "followed_user"), name="unique_relation"),
        ),
        migrations.AddConstraint(
            model_name="followrelation",
            constraint=models.CheckConstraint(
                check=models.Q(("following_user", models.F("followed_user")), _negated=True),
                name="cannot_follow_myself",
            ),
        ),
    ]
