# Generated by Django 4.1.10 on 2023-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_followrelation_unique_relation_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="followrelation",
            name="unique_relation",
        ),
        migrations.AddConstraint(
            model_name="followrelation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("followed_user__isnull", False), ("following_user__isnull", False)),
                fields=("following_user", "followed_user"),
                name="unique_relation",
                violation_error_message="同じユーザーを複数回フォローすることはできません",
            ),
        ),
    ]
