# Generated by Django 4.1.10 on 2023-08-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.TextField(),
        ),
    ]
