# Generated by Django 4.1.10 on 2023-08-25 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="tweets",
            new_name="text",
        ),
    ]
